ground_segmentation:
  ros__parameters:
    # pre processing
    target_frame: "base_link"
    #target_frame: "velodyne_top"
    #target_frame: "husky"
    maxX:  100.0
    minX: -100.0
    maxY:  20.0
    minY: -20.0
    maxZ:  10.0
    minZ: -10.0
    downsample: true
    downsample_distance: 0.2

    # ground detection
    grid_type: 0
    radialCellSize: 2.0
    angularCellSize: 0.349066
    cellSizeX: 2.0
    cellSizeY: 2.0
    cellSizeZ: 10.0
    gridmaxX: 100.0
    gridmaxY: 20.0 
    gridmaxZ: 10.0
    startCellDistanceThreshold: 30.0
    slopeThresholdDegrees: 30.0
    groundInlierThreshold: 0.1
    returnGroundPoints: true
    neighborsIndexThreshold: 1
    minPoints: 5
    ransac_iterations: 50