ground_segmentation:
  ros__parameters:
    # pre processing
    target_frame: "base_link"
    maxX:  50.0
    minX: -50.0
    maxY:  50.0
    minY: -50.0
    maxZ:  50.0
    minZ: -50.0
    downsample: true
    downsample_distance: 0.1

    # ground detection
    grid_type: 0
    radialCellSize: 2.0
    angularCellSize: 0.349066
    cellSizeX: 2.0
    cellSizeY: 2.0
    cellSizeZ: 10.0
    gridmaxX: 50.0
    gridmaxY: 50.0 
    gridmaxZ: 50.0
    startCellDistanceThreshold: 20.0
    slopeThresholdDegrees: 30.0
    groundInlierThreshold: 0.1
    returnGroundPoints: true
    neighborsIndexThreshold: 1
    minPoints: 5
    ransac_iterations: 50