ground_segmentation:
  ros__parameters:
    # pre/post processing
    robot_frame: "arter/velodyne_link"
    maxX:  100.0
    minX: -100.0
    maxY:  100.0
    minY: -100.0
    maxZ:  100.0
    minZ: -100.0
    downsample: false
    downsample_resolution: 0.1
    lidar_to_ground: -1.73
    transform_tolerance: 0.1

    ##ground detection
    cellSizeX: 1.5
    cellSizeY: 1.0
    cellSizeZ: 1.5
    slopeThresholdDegrees: 30.0
    groundInlierThreshold: 0.125
    centroidSearchRadius: 5.0
    use_imu_orientation: false

    #debug
    show_benchmark: true