ground_segmentation:
  ros__parameters:
    # pre processing
    robot_frame: "base_link"
    maxX:  80.0
    minX: -80.0
    maxY:  80.0
    minY: -80.0
    maxZ:  80.0
    minZ: -80.0
    downsample: false
    downsample_resolution: 0.1

    # ground detection
    cellSizeX: 2.0
    cellSizeY: 2.0
    cellSizeZ: 10.0
    startCellDistanceThreshold: 10.0
    slopeThresholdDegrees: 30.0
    groundInlierThreshold: 0.1
    use_imu_orientation: true

    #debug
    show_benchmark: false
    show_seed_cells: false
    show_grid: false
