ground_segmentation:
  ros__parameters:
    # pre/post processing
    robot_frame: "base_link"
    maxX:  40.0
    minX: -40.0
    maxY:  40.0
    minY: -40.0
    maxZ:  40.0
    minZ: -40.0
    downsample: false
    downsample_resolution: 0.1
    dist_to_ground: 1.8
    robot_radius: 2.0
    compute_clusters: false

    ##ground detection
    cellSizeX: 1.5
    cellSizeY: 1.5
    cellSizeZ: 10.0
    slopeThresholdDegrees: 30.0
    groundInlierThreshold: 0.1
    use_imu_orientation: false

    #debug
    show_benchmark: true
    show_grid: false