ground_segmentation:
  ros__parameters:
    # pre processing
    target_frame: "base_link"
    #target_frame: "base_link/base_link"
    #target_frame: "velodyne"
    #target_frame: "laser_data_frame"
    #target_frame: "arter/base_link"
    #target_frame: "zed2_left_camera_frame"
    #target_frame: "ouster00"
    #target_frame: "map"
    #target_frame: "velodyne_top"
    #target_frame: "husky"
    #target_frame: "os1_lidar"
    #target_frame: "ouster1/os1_lidar"
    #target_frame: "lexus3/os_center_a_laser_data_frame"
    #target_frame: "os_sensor"
    maxX:  80.0
    minX: -80.0
    maxY:  80.0
    minY: -80.0
    maxZ:  80.0
    minZ: -80.0
    downsample: false
    downsample_resolution: 0.1

    # ground detection
    cellSizeX: 2.0
    cellSizeY: 2.0
    cellSizeZ: 4.0
    startCellDistanceThreshold: 10.0
    slopeThresholdDegrees: 30.0
    groundInlierThreshold: 0.1
    neighborsIndexThreshold: 3
    minPoints: 5
    ransac_iterations: 1000

    #post processing
    use_convex_hulls_3d: false

    #debug
    show_benchmark: true
    show_seed_cells: true
